export { default as Header } from './common/Header';
export { default as MainWrap } from './main/MainWrap';
export { default as Slide } from './main/Slide';
export { default as SlideContent } from './main/SlideContent';
export { default as ProductWrap } from './product/ProductWrap';
export { default as ProductDetailWrap } from './productDetail/ProductDetailWrap';
export { default as SearchWrap } from './search/SearchWrap';
export { default as TestWrap } from './test/TestWrap';
export { default as Footer } from './common/Footer';
